// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHAYnlk8V00ux61VfA0lBFCxrbWO_apM',
    appId: '1:829051846535:android:f258de8582d3ab4fcc1d22',
    messagingSenderId: '829051846535',
    projectId: 'flutter-chat-app-d380e',
    storageBucket: 'flutter-chat-app-d380e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9JO0yW4ojuM7-35Y5Vc6tPQ9K4VSM1A',
    appId: '1:829051846535:ios:15f2dfa6749e6ab9cc1d22',
    messagingSenderId: '829051846535',
    projectId: 'flutter-chat-app-d380e',
    storageBucket: 'flutter-chat-app-d380e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAldddZdMcpw_vTU-DzhBrC5mU1Ww-R6cU',
    appId: '1:829051846535:web:9b5f7f2667bca250cc1d22',
    messagingSenderId: '829051846535',
    projectId: 'flutter-chat-app-d380e',
    authDomain: 'flutter-chat-app-d380e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d380e.firebasestorage.app',
    measurementId: 'G-10DL43J883',
  );

}